### ISSUE TITLE
Attachment Menu PNG Issue

### ISSUE THREAD

**Issue by HysteriaRP** [loljoshie/lj-inventory#108]
So all images work, except the attachment_image pngs, the gun photos work on the attachment menu screen, but none of the attachment pngs show, its a broken page with the label of the image only.
![FiveM_b2699_GTAProcess_OaTUxbMlN0](https://user-images.githubusercontent.com/87357750/208281951-150ccdd4-a5e2-42d4-93ea-538d67ac2e6f.png)

**Comment by MonkeyWhisper** [comment]
Issue not duplicated on local host
