### ISSUE TITLE
Items disappear after restart/reconnect

### ISSUE THREAD

**Issue by BrianMaybach** [loljoshie/lj-inventory#113]
I don't know why, but after I reconnect on my Server, my Items are gone. Can you help me?

**Comment by Tomogunchi** [comment]
Same issue here, also the custom color settings aren't making any changes to the UI

**Comment by Tomogunchi** [comment]
Same issue here, items disappear from inventory after restart

**Comment by BrianMaybach** [comment]
Already tried to reinstall the server but nothing changes maybe somebody can help us

**Comment by BrianMaybach** [comment]
3 Months ago there was the same issue. They fixed it by renaming qb-inventory to lj-inventory in all files. I tried to do it too, but no changes. Then i updated my oxmysql and it changed nothing too.

**Comment by lawfulbrick09** [comment]
Go to qb-core/server/players and replace everything that says qb-inventory with lj-inventory (old qbcore on top)

**Comment by BrianMaybach** [comment]
Thank you so much
