### ISSUE TITLE
No Gun Animation

### ISSUE THREAD

**Issue by RayaanUddin** [loljoshie/lj-inventory#114]
Please help me. Get no gun animation

**Comment by lawfulbrick09** [comment]
Go to qb/qb-smallresources/client/weapondraw and add your weapons their

**Comment by SalfordJY** [comment]
yeah i am having the same issue, the weapons are in the weapon draw files and still not working

**Comment by RaelesPLS** [comment]
Same here and all my weapon was in the Weapondraw.

any fix ?
