### ISSUE TITLE
Crafting not working

### ISSUE THREAD

**Issue by SwagDaddyBrad** [loljoshie/lj-inventory#119]
I followed all directions in the README.md and changed every instance of qb-inventory to lj-inventory
However, now the crafting system is not working. Prior to installing lj-inventory I was able to go up to any toolbox and press E to craft. I was hoping this would work when I transferred everything over but it did not. Any help would be much appreciated :)

![image](https://user-images.githubusercontent.com/64005388/210233766-8efbf4d1-19cd-4b62-b796-9807dd0e3d2d.png)

**Comment by SwagDaddyBrad** [comment]
Note: I am not using qb-target. I just want players to press E to craft. I can send pics and images of anything you might need to help fix this problem

**Comment by Ginjakz** [comment]
Same issue here but with using qb-target
