### ISSUE TITLE
AddTargetModel error in client/main.lua

### ISSUE THREAD

**Issue by shane0011** [loljoshie/lj-inventory#135]
Hi, i got this error, what can be the problem?
![image](https://user-images.githubusercontent.com/87019884/219027428-f549d073-9f5a-4400-8e95-038d41f1de63.png)
![image](https://user-images.githubusercontent.com/87019884/219027598-9f27d5df-c526-4dad-a3f9-1f0b4299565e.png)

**Comment by MonkeyWhisper** [comment]
This is not for support
