### ISSUE TITLE
Weapon Draw animation not working

### ISSUE THREAD

**Issue by Noti027** [loljoshie/lj-inventory#139]
The animation on the holster animation and behind the back animation are not working anymore when you install this inventory. The script for the animation in smallresources it also says that this will only work for qb-inventory but do people actually fix this or no because like every server i have joined with this server the animation just works perfect

**Comment by paruthepro** [comment]
I'll look into this and create a PR if needed

**Comment by SukiTibi** [comment]
Same here, doesn't work for me unfortunately.

**Comment by RayaanUddin** [comment]
If your inventory is not named qb-inventory, then go into your qb-smallresources/client/weapondraw.lua, and comment out this line 
![image](https://user-images.githubusercontent.com/91953921/223482759-555ab282-6c26-4a01-b9a5-478bd1df892f.png)
i.
Some inventories dont trigger the even, where you have to add it manually to your inventorys client script.
