### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TheRaskillDev** [loljoshie/lj-inventory#14]
stuck mouse cursor when inventroy close

**Comment by loljoshie** [comment]
Hey! I'd imagine it's because you've changed the resource name therefore you'll also have to change the NUI Callback part found in the JavaScript file for it to get the right events

**Comment by baytowntexas** [comment]
im in the same situation as he is i didnt rename them i just dragged the 3 files like told on readme

**Comment by loljoshie** [comment]
Sorry for the late reply, hopefully you figure out your issue in that time but if not make sure you don't have -main on the end of the folder after downloading from GitHub.
