### ISSUE TITLE
Items lost when transferring to a full inventory

### ISSUE THREAD

**Issue by jellyton69** [loljoshie/lj-inventory#140]
https://medal.tv/games/gta-v/clips/Wibbwhae2J0_-/d1337ehATEjW?invite=cr-MSxMM0osODI4MzM4NjIs

This clip shows a player attempting to transfer 50 items to her main inventory from a stash. It allows her to move over the items but it notifies the player that the inventory is full. However, it doesn't put the items back where they were it just allows the transfer to occur without saving the new data.

This is a major issue with qb-inventory as well, there's nothing that blocks the action from visually occurring, and it never reverts the action when it does go through.

**Comment by CptNoHand** [comment]
I agree this happens quite often with high number stacks.

**Comment by MonkeyWhisper** [comment]
Yeah, this is quite an EXTENSIVE issue 

If it gets fixed on qbcore, we'll push a PR here
