### ISSUE TITLE
QB-Smallresources WeaponDraw doesn't work

### ISSUE THREAD

**Issue by ShortKeeper** [loljoshie/lj-inventory#157]
Running into an issue with qb-smallreasources/weapondraw.lua where replacing the qb-inventory with lj-inventory doesn't work properly. It is not longer adding the quicker draw time with a holster or the new animation while wearing said holster.

**Comment by ChickenDipper1** [comment]
Open weapondraw.lua, remove the code that is checking for qb-inventory or change it to say lj-inventory.

**Comment by ShortKeeper** [comment]
We did that and it still isn't doing it, that was the first thing that I checked for.
