### ISSUE TITLE
Got this error overnight and i dont know why or whats going on

### ISSUE THREAD

**Issue by CFenix123** [loljoshie/lj-inventory#166]
[ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:468: attempt to index a nil value (field 'Items')
[ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:468: attempt to index a nil value (field 'Items')
[ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:468: attempt to index a nil value (field 'Items')
[ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:2039: attempt to index a nil value (field 'Items')

**Comment by Ashenboy** [comment]
> [ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:468: attempt to index a nil value (field 'Items')
> [ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:468: attempt to index a nil value (field 'Items')
> [ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:468: attempt to index a nil value (field 'Items')
> [ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:2039: attempt to index a nil value (field 'Items')

Check your items.lua in qbcore->shared folder
