### ISSUE TITLE
Mouse laggy

### ISSUE THREAD

**Issue by LoRDWiZz** [loljoshie/lj-inventory#17]
When I drag the item in this area mouse laggy 
![image](https://user-images.githubusercontent.com/66243394/148693810-3f18c908-2911-4ad5-be86-7857ffdbd50a.png)

**Comment by gitgaming21** [comment]
yer im having it as well 
https://gyazo.com/31575aa00ea3be5deda81bffb8e1d379
plus iv just seen this happen as well 
https://gyazo.com/46d1182166356dec883de1040f0c53ab

**Comment by Kohiq** [comment]
In the css replace this:
.item-slot:hover {
    transition: ease 0.3s;
    background-color: rgb(48 48 56 / 30%) !important;
}

by this:
.item-slot:hover {
    background-color: rgb(48 48 56 / 30%) !important;
}

**Comment by loljoshie** [comment]
Wasn't able to return to this resource until now! Thanks for sending that in for the community
