### ISSUE TITLE
items dissapear from my inventory

### ISSUE THREAD

**Issue by Denyss600** [loljoshie/lj-inventory#172]
I have default QBCore fresh installed, and the first thing I did, is to install & follow everything, including the .sql file provided. When creating a character I'm getting the starting items, like the phone and license etc but after disconnecting from the server and join back again everything from my inventory disappear.
![Screenshot_1](https://github.com/loljoshie/lj-inventory/assets/137230286/d1870aa5-dec0-45fb-b14d-dc00deb14d08)
![Screenshot_2](https://github.com/loljoshie/lj-inventory/assets/137230286/4621a4c4-e735-4fb3-ac75-396622a673f3)

**Comment by Friskky1** [comment]
Let me know if you get a fix

**Comment by Denyss600** [comment]
> Let me know if you get a fix

I have not figured it out... I'm still looking for help
