### ISSUE TITLE
lj inventory server qb core neeed help with this error tried to open inv and it said this

### ISSUE THREAD

**Issue by ticcss714** [loljoshie/lj-inventory#179]
![image](https://github.com/loljoshie/lj-inventory/assets/146783410/942e780f-38a2-4189-b21d-0de03bd89951)
![image](https://github.com/loljoshie/lj-inventory/assets/146783410/437956fb-b559-4fcb-819e-b87ca1c693a9)

**Comment by AntonMars** [comment]
Closed as completed basically means he doesn't know how to fix it.
