### ISSUE TITLE
Not professional at all!

### ISSUE THREAD

**Issue by AntonMars** [loljoshie/lj-inventory#180]
@MonkeyWhisper As a "developer" in the GitHub community, you may want to review your conduct regarding feedback. I've had a few instances where I have posted regarding issues/bugs on products you "oversee", and the standard response from you is to close the issue, without any sort of indication of whether it has been resolved or not. This is not the way the industry works, and goes against the spirit of using GitHub as a repository of your products.

Upon further research, I've noticed you regularly close issues without replying, leaving us with no idea if the issue has been resolved or not. May I request that you respond with a short sentence, either informing us that the issue has been resolved with an update, that you are working on the issue, or what we can do to solve the problem? We do go through the old issues to see if other people have had the same issue before, and a closed issue without any response is of no help.

Sticking your head into the sand, will not make the problem go away. Please take this as constructive feedback, and make the community better, not worse.

**Comment by MonkeyWhisper** [comment]
> @MonkeyWhisper As a "developer" in the GitHub community, you may want to review your conduct regarding feedback. I've had a few instances where I have posted regarding issues/bugs on products you "oversee", and the standard response from you is to close the issue, without any sort of indication of whether it has been resolved or not. This is not the way the industry works, and goes against the spirit of using GitHub as a repository of your products.
> 
> Upon further research, I've noticed you regularly close issues without replying, leaving us with no idea if the issue has been resolved or not. May I request that you respond with a short sentence, either informing us that the issue has been resolved with an update, that you are working on the issue, or what we can do to solve the problem? We do go through the old issues to see if other people have had the same issue before, and a closed issue without any response is of no help.
> 
> Sticking your head into the sand, will not make the problem go away. Please take this as constructive feedback, and make the community better, not worse.

Life is hard wear a helmet

Grab a ticket and wait for me to give a fuck about your feelings and your poorly written ChatGPT essay
