### ISSUE TITLE
> @MonkeyWhisper As a "developer" in the GitHub community, you may want to review your conduct regarding feedback. I've had a few instances where I have posted regarding issues/bugs on products you "oversee", and the standard response from you is to close the issue, without any sort of indication of whether it has been resolved or not. This is not the way the industry works, and goes against the spirit of using GitHub as a repository of your products.

### ISSUE THREAD

**Issue by AntonMars** [loljoshie/lj-inventory#181]
> @MonkeyWhisper As a "developer" in the GitHub community, you may want to review your conduct regarding feedback. I've had a few instances where I have posted regarding issues/bugs on products you "oversee", and the standard response from you is to close the issue, without any sort of indication of whether it has been resolved or not. This is not the way the industry works, and goes against the spirit of using GitHub as a repository of your products.
> 
> Upon further research, I've noticed you regularly close issues without replying, leaving us with no idea if the issue has been resolved or not. May I request that you respond with a short sentence, either informing us that the issue has been resolved with an update, that you are working on the issue, or what we can do to solve the problem? We do go through the old issues to see if other people have had the same issue before, and a closed issue without any response is of no help.
> 
> Sticking your head into the sand, will not make the problem go away. Please take this as constructive feedback, and make the community better, not worse.

Life is hard wear a helmet

Grab a ticket and wait for me to give a fuck about your feelings and your poorly written ChatGPT essay

_Originally posted by @MonkeyWhisper in https://github.com/loljoshie/lj-inventory/issues/180#issuecomment-1769139891_

**Comment by AntonMars** [comment]
Apologies to the community and Github for this thread, which is threatening to turn into a flamewar, but after this I'm stopping.

The gentleman who speaks to monkeys needs to hear this, and apparently, this is the only way to get his attention since his full-time job at Project Sloth seems to be closing tickets without actually doing anything about them.

No sir, Chat did not assist me in writing this or any previous messages, and if you knew anything about AI, you would realize that explaining the situation to Chat would be more work than the actual response.
No sir, life is only hard if you go through it thinking that everything and everybody is a nuisance that needs to be sworn at to make you feel better about your shitty existence.
Lastly, closing tickets without responding does not instill any confidence in your products. In fact, I would venture a guess that the people who got the door slammed in their faces by you, are already using someone else's scripts, begging the question: What are you doing here?

Your repository subheading: 
Passionate developers and designers with a primary focus toward providing quality resources and user experience that are open source.
- You're not passionate, you're just a grumpy old fart
- You're not a developer because a developer actually cares about fixing their bugs
- You don't provide quality resources because the same issues I asked about many weeks ago in your ps-housing script are still there.
- The user experience in interactions with you sucks.
- And "toward" should actually be "towards"

Now do what you normally do, and close this issue. Maybe the community won't see it. Oh wait, they will...

**Comment by MonkeyWhisper** [comment]
> Apologies to the community and Github for this thread, which is threatening to turn into a flamewar, but after this I'm stopping.
> 
> The gentleman who speaks to monkeys needs to hear this, and apparently, this is the only way to get his attention since his full-time job at Project Sloth seems to be closing tickets without actually doing anything about them.
> 
> No sir, Chat did not assist me in writing this or any previous messages, and if you knew anything about AI, you would realize that explaining the situation to Chat would be more work than the actual response. No sir, life is only hard if you go through it thinking that everything and everybody is a nuisance that needs to be sworn at to make you feel better about your shitty existence. Lastly, closing tickets without responding does not instill any confidence in your products. In fact, I would venture a guess that the people who got the door slammed in their faces by you, are already using someone else's scripts, begging the question: What are you doing here?
> 
> Your repository subheading: Passionate developers and designers with a primary focus toward providing quality resources and user experience that are open source.
> 
> * You're not passionate, you're just a grumpy old fart
> * You're not a developer because a developer actually cares about fixing their bugs
> * You don't provide quality resources because the same issues I asked about many weeks ago in your ps-housing script are still there.
> * The user experience in interactions with you sucks.
> * And "toward" should actually be "towards"
> 
> Now do what you normally do, and close this issue. Maybe the community won't see it. Oh wait, they will...

I'm not reading all of this because unlike you I have an amazing life, fucking boomer 😂
