### ISSUE TITLE
No such export CreateShop in resource lj-inventory

### ISSUE THREAD

**Issue by Bajen332** [loljoshie/lj-inventory#190]
![image](https://github.com/loljoshie/lj-inventory/assets/175144623/be6932f1-bee7-42c3-9fac-cd9aae70e236)

**Comment by madmechanic187** [comment]
same here anyone have a fix updated qb-shops now its doing this replaced the main with the exports

**Comment by johandrehoon** [comment]
Sane here any luck someone been sitting hours looking for a fix

**Comment by PandaBearGaming96** [comment]
[script:qb-management] SCRIPT ERROR: @qb-management/server/sv_boss.lua:66: No such export OpenInventory in resource lj-inventory
