### ISSUE TITLE
Cannot add items to craft 

### ISSUE THREAD

**Issue by Ashenboy** [loljoshie/lj-inventory#36]
![image](https://user-images.githubusercontent.com/66189779/157998979-bb6cf65b-285a-479a-b3ae-5c6c5255fa2b.png)

**Comment by ImpulseFPS** [comment]
You have to add a description for items under the line 161

**Comment by Ashenboy** [comment]
> You have to add a description for items under the line 161
in js/app.js ?

**Comment by ImpulseFPS** [comment]
client.lua

**Comment by Ashenboy** [comment]
> client.lua

oh thanks
