### ISSUE TITLE
Not showing required items for weapons

### ISSUE THREAD

**Issue by Ashenboy** [loljoshie/lj-inventory#38]
![Screenshot (220)](https://user-images.githubusercontent.com/66189779/158230489-a353f590-b8e1-4819-93bc-2653b7227bd6.png)
![Screenshot (221)](https://user-images.githubusercontent.com/66189779/158230531-69e11f10-1ee0-4d1a-aa63-b8b62284d88b.png)

**Comment by zh-development** [comment]
did you rember to add the infomation on line 161 in this function

local function ItemsToItemInfo()
	itemInfos = {
	
	}
