### ISSUE TITLE
use item css

### ISSUE THREAD

**Issue by KenanDK666** [loljoshie/lj-inventory#4]
im having a small issue when i use an item on 2560x1440 but if set my monitor to 1920x1080 there is no issue, is there an easy way to make sure it fits every resolution?

![image](https://user-images.githubusercontent.com/61769938/146352709-efd23fe9-629d-4d94-abc0-6467631b71f1.png)

**Comment by loljoshie** [comment]
Plan on doing an update that covers UltraWide support just like with my hud. This is just initial release to get all the bugs figured out and fixed.
