### ISSUE TITLE
[FEATURE REQUEST] Default Quantity / Dropping more than one item

### ISSUE THREAD

**Issue by GLaZeD-DoHNuTz** [loljoshie/lj-inventory#47]
First off, awesome job!

These two requests may be ridiculous but I wanted to ask anyways.

I was wondering if it would make sense to default the quantity to a value of 1

Example: If a player is shopping in a store, and they right-click an item they can select one item, however, if they drag from the right side to the left side, they have to set the quantity to 1 before dragging it over.

As for dropping an item, is there a way to eliminate the inventory closing once someone drops the first item, because if you have to drop multiple items, you have to drop one item, then go back into the inventory and drop the rest of the items.

THANK YOU!

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
