### ISSUE TITLE
Inventory is randomly assigning things to hotbar slots.

### ISSUE THREAD

**Issue by Wendigo23** [loljoshie/lj-inventory#48]
Anything that is in the hotbar, will function properly for a while.. then suddenly, the inventory system will assign random items that are already in your inventory, into one of the hotbar slots. Items will have to be constantly shuffled out into other slots, by opening and moving and closing and doing such over and over again, for the issue to clear up. Sometimes, you can log out and log back in and that will fix it, but there doesnt seem to be any bugs or errors, and no known catalysts.

**Comment by tom091291** [comment]
i have a similar issue on our server aswell

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
