### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by emanuelgggggggg** [loljoshie/lj-inventory#50]
![image](https://user-images.githubusercontent.com/47868954/163653285-d22dfc9a-042f-487e-96b4-efab98d23d49.png)
someone can help me pls ????

**Comment by zh-development** [comment]
did you rember to rename the folder and remove the -main from it

**Comment by Purenoiz** [comment]
I have the same problem and I changed the folder name

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
