### ISSUE TITLE
Huge display

### ISSUE THREAD

**Issue by AltyS-CZ** [loljoshie/lj-inventory#51]
I need to scale the inventory to make it smaller. It's fcking huge. How do i do this?

**Comment by sol-fitzy** [comment]
It's in the HTML directory

**Comment by AltyS-CZ** [comment]
Be more specific please. Where in html? Where specifically? just saying HTML doesn't help? ui.html? in css? in js?

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
