### ISSUE TITLE
[BUG] css responsive

### ISSUE THREAD

**Issue by luizgustavof** [loljoshie/lj-inventory#52]
not responsive

![image](https://user-images.githubusercontent.com/89892998/166077814-39935ac7-c1fa-48a6-a5d9-d72b885408dd.png)

**Comment by iHemeda** [comment]
i have the same issue too !!
![Screenshot_1](https://user-images.githubusercontent.com/56701171/166895515-f0bb2415-8e40-48da-a4a3-3f4dfc69df35.png)

**Comment by iHemeda** [comment]
My Resolution is : 1920x1200

**Comment by Glunkussss** [comment]
> My Resolution is : 1920x1200

I think is for the think like 4:3 if u have it put 16;9

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
