### ISSUE TITLE
Player items in apartment stashes and trunks going missing?

### ISSUE THREAD

**Issue by nzkfc** [loljoshie/lj-inventory#53]
We have had an influx of player tickets for items going missing when they put it into their stashes or trunks, I know qb framework handles some of this but I noticed someone in qb-core discord also has the same issue recently.

Checking logs, I can see that they put things in, then go back and it's not there?

**Comment by nzkfc** [comment]
Another example: https://cdn.discordapp.com/attachments/974564396149927936/974917846519939072/MedalTVFiveM20220514180824_Trim.mp4

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
