### ISSUE TITLE
Give Item Duplicate Fix

### ISSUE THREAD

**Issue by NoSkills7** [loljoshie/lj-inventory#55]
If the other player's inventory is full and you try to give them an item, you will keep that item on you and it will create a duplicate of it on the ground.

**Comment by NoSkills7** [comment]
Shouldn't have named it "Fix" lmao I meant "Bug"

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
