### ISSUE TITLE
[BUG] Overweight bug in car trunk

### ISSUE THREAD

**Issue by marknguyen13** [loljoshie/lj-inventory#56]
when the car/motorbike trunk is entirely full, there's a bug that can make players put more items into the trunk even if it has already full weight.
https://streamable.com/znnv36

**Comment by 19adorest** [comment]
Yeah im facing this problems too.
https://streamable.com/86owkg

**Comment by MonkeyWhisper** [comment]
This is not for support. If you need help, join our discord. 

https://discord.gg/projectsloth
