### ISSUE TITLE
We need a more updated version because qbcore have had a huge update

### ISSUE THREAD

**Issue by J2W1905** [loljoshie/lj-inventory#73]

**Comment by Kolvyy** [comment]
nice

**Comment by penguforstarter** [comment]
agreed this is needed asap as with the new core update for qb-core it brakes the inventory todo with itemslots and adding items it seem

**Comment by Beoriginalpt** [comment]
I've been having this issue as well it gives me this when  i try to add any item to the inventory from command /giveitem

#> [ script:lj-inventory] SCRIPT ERROR: @lj-inventory/server/main.lua:1527: attempt to call a nil value (field 'AddItem')
> [ script:lj-inventory] > ref (@qb-core/server/commands.lua:31)
> [      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:479: attempt to concatenate a nil value (local 'err')

 and if i pickup any item it just dont calls for any error and just keep the inventory empty.
i think is something abou the way that commands works and the code for the inventory needs to be updated to get the right answer. 

I've tryed keeping the qb-inventory at the same time as lj-inventory and it fixes the inventory errors cuz its grabing the answers given to qb-inventory so its no something major i just lack the skills to fix it by myself i'm going trough both scripts but they are  so different for the same functions that due my lack of knowladge i cant translate to a code correction.

**Comment by SKITTLE6969** [comment]
yes please

**Comment by LucasVioa** [comment]
Please! New Uptade!
