### ISSUE TITLE
[BUG] "Dropped None"

### ISSUE THREAD

**Issue by scrubh** [loljoshie/lj-inventory#9]
Sometimes the dropped item dissapear if you open the inventory too far away or open it many times, there is drop marker but when you view it there is text Dropped None and the whole inventory is bugged, this happens to original qb inventory too :(
![image](https://user-images.githubusercontent.com/91434926/146491586-8c8f1951-02c0-4695-b00a-4b6ee76b7d66.png)

**Comment by za3emtgf** [comment]
also me :)
![image](https://user-images.githubusercontent.com/77130312/146960187-549312a3-7be6-4eff-9967-b3364897dc92.png)
![image](https://user-images.githubusercontent.com/77130312/146960235-62bb6415-fe38-43de-b093-f45e5aad56a6.png)
![image](https://user-images.githubusercontent.com/77130312/146960290-edfc9ec7-eb25-4664-8f01-328ddeb37296.png)

**Comment by Spencer10798** [comment]
This issue exists for me as well, hoping there's a fix to it, otherwise players can permanently lose items while trying to drop them on the ground for other players to take.

**Comment by BlueSky-fur** [comment]
We dont have that issue.

**Comment by Spencer10798** [comment]
> We dont have that issue.

You're using this, lj-inventory, and have no players experiencing this issue? 
Can I jump on your server to test it out? That'd be a significant development if you've found a way to get around this issue. I think it plagues many inventory resources.

**Comment by whoops1e** [comment]
> This issue exists for me as well, hoping there's a fix to it, otherwise players can permanently lose items while trying to drop them on the ground for other players to take.

+1, having same issues.

**Comment by darknight2590** [comment]
https://github.com/qbcore-framework/qb-inventory/pull/193
