### ISSUE TITLE
Items disappear when loading back in

### ISSUE THREAD

**Issue by virtuseee** [loljoshie/lj-inventory#93]
So when you have an item, when you F8 quit and join back in they are all gone, BUT when I switch back to the old qb-core it works fine can someone help me

**Comment by Ford1337** [comment]
I have the same issue, latest QBCore everything up-to-date.

Only having issues that inventory is not getting saved.

**Comment by FIB3R-TTV** [comment]
![image](https://user-images.githubusercontent.com/92599608/194299793-bf7d83f7-d906-4d17-a9f1-b01a8e63df2e.png)
i did this and it fixed it

**Comment by offsetgamer** [comment]
any fix on this or better inventory?
