### ISSUE TITLE
No Such Export LoadInventory (qb-multicharacter)

### ISSUE THREAD

**Issue by F8Hyper** [loljoshie/lj-inventory#98]
Receiving this console error after loading in and selecting a character resulting in not being able to load in stuck on black loading screen fully

SCRIPT ERROR: @qb-core/server/player.lua:162: No such export LoadInventory in resource lj-inventory

This comes after changing all 'qb-inventory' items in QB-core to 'lj-inventory'

This Follows the above error

[script:qb-multichara] > <unknown> (@oxmysql/dist/build.js:22441)
[script:qb-multichara] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:qb-multichara] > async rawExecute (@oxmysql/dist/build.js:22394)
[script:qb-multichara] 
[script:qb-multichara] > handler (@qb-multicharacter/server/main.lua:91)
[script:qb-multichara] > <unknown> (@oxmysql/dist/build.js:22441)
[script:qb-multichara] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:qb-multichara] > async rawExecute (@oxmysql/dist/build.js:22394)

**Comment by F8Hyper** [comment]
[CitizenFX_log_2022-10-26T045301.log](https://github.com/loljoshie/lj-inventory/files/9866374/CitizenFX_log_2022-10-26T045301.log)
Also Receiving AN Error In F8 LOG

**Comment by ImpulseFPS** [comment]
You are using the outdated version of lj-inventory with updated qb-core version :D
