### ISSUE TITLE
Stash Item Duplicate Problem

### ISSUE THREAD

**Issue by kadiratesdev** [loljoshie/lj-inventory#99]
There seems to be a dupe issue which you would need to open your stash and put in items then close out of it. After that when you open stash again and take the items and then disconnect instantly you will have the items inside the stash and also your inventory.

You can see how this method works from the video : https://streamable.com/zp0blf

**Comment by IKKaybe** [comment]
I have seen this happen also!

**Comment by EstablishSolutions** [comment]
https://github.com/loljoshie/lj-inventory/pull/91

**Comment by cheatchansovoth** [comment]
still no solution for it.it has become a serious issue in my server

**Comment by MonkeyWhisper** [comment]
Closing so noisy players won't see this, will see how we can push a fix for this.
